// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCzfhTKsnF_OfB68lBWT1TiLfaRAQk-Z4',
    appId: '1:787052337803:web:c6af7e2d462ff0fe3b528e',
    messagingSenderId: '787052337803',
    projectId: 'rangadda-57efc',
    authDomain: 'rangadda-57efc.firebaseapp.com',
    storageBucket: 'rangadda-57efc.firebasestorage.app',
    measurementId: 'G-4FKQZKN129',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSVPRW1SiF7mDNPfKcWMhhN8NSaYce4Io',
    appId: '1:787052337803:android:46faca76004e8ad63b528e',
    messagingSenderId: '787052337803',
    projectId: 'rangadda-57efc',
    storageBucket: 'rangadda-57efc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz9Z4Dzh4CNe14A3f1fITJxYCxhdgkMB8',
    appId: '1:787052337803:ios:830c1b8a13d276d93b528e',
    messagingSenderId: '787052337803',
    projectId: 'rangadda-57efc',
    storageBucket: 'rangadda-57efc.firebasestorage.app',
    iosBundleId: 'com.marbo.rangAdda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz9Z4Dzh4CNe14A3f1fITJxYCxhdgkMB8',
    appId: '1:787052337803:ios:830c1b8a13d276d93b528e',
    messagingSenderId: '787052337803',
    projectId: 'rangadda-57efc',
    storageBucket: 'rangadda-57efc.firebasestorage.app',
    iosBundleId: 'com.marbo.rangAdda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCzfhTKsnF_OfB68lBWT1TiLfaRAQk-Z4',
    appId: '1:787052337803:web:b92e445d7f431bcd3b528e',
    messagingSenderId: '787052337803',
    projectId: 'rangadda-57efc',
    authDomain: 'rangadda-57efc.firebaseapp.com',
    storageBucket: 'rangadda-57efc.firebasestorage.app',
    measurementId: 'G-491W8BF525',
  );
}
